name: Basic Python Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.8
        mamba-version: "*"
        use-mamba: true
    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        conda env list
    - name: Python info
      shell: bash -l {0}
      run: |
        which python
        python --version
    - name: Show environment variables
      shell: bash -l {0}
      run: |
        env | sort
    - name: Install conda dependencies (into base)
      shell: bash -l {0}
      run: |
        mamba env update -n base -f environment_testing.yml
    - name: Install with development dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip       

    - name: Install requirements
      shell: bash
      run: |
        conda activate ms-gen
        pip install -r requirements_testing.txt
        pip install pytest

    - name: Show environment
      shell: bash
      run: |
        conda activate ms-gen
        pip list
        conda list
        conda info
  
    - name: Install package
      shell: bash
      run: |
        conda activate ms-gen
        pip install -e .

    - name: Run tests with pytest
      shell: bash
      run: |
        conda activate ms-gen
        pytest
