name: Basic Python Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        activate-environment: ms-gen
        environment-file: environment_testing.yml
        use-mamba: true
        auto-activate-base: false
        
    - name: Initialize Conda
      run: echo ". /usr/share/miniconda/etc/profile.d/conda.sh" >> $GITHUB_ENV

    - name: Install requirements
      shell: bash
      run: |
        conda activate ms-gen
        pip install -r requirements_testing.txt
        pip install pytest

    - name: Show environment
      shell: bash
      run: |
        conda activate ms-gen
        pip list
        conda list
        conda info
  
    - name: Install package
      shell: bash
      run: |
        conda activate ms-gen
        pip install -e .

    - name: Run tests with pytest
      shell: bash
      run: |
        conda activate ms-gen
        pytest
