name: Basic Python Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        activate-environment: ms-gen
        environment-file: environment_testing.yml

    - name: Install requirements
      shell: bash
      run: |
        pip install -r requirements_testing.txt
        pip install pytest

    - name: Pip list
      shell: bash
      run: |
        pip list
  
    - name: Install package
      shell: bash
      run: |
        pip install -e .

    - name: Run tests with pytest
      shell: bash
      run: |
        pytest
