name: Basic Python Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        activate-environment: ms-gen
        environment-file: etc/example-environment.yml

    - name: Set up Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        activate-environment: ms-gen
        environment-file: environment.yml

    - name: Install requirements
      shell: bash
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Pip list
      shell: bash
      run: |
        pip list
  
    - name: Install package
      shell: bash
      run: |
        python setup.py develop

    - name: Run tests with pytest
      shell: bash
      run: |
        mamba activate ms-gen
        pytest
